Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-8"
  c.vm.hostname = "vanilla-rhel-8.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/wdower/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-redhat-enterprise-linux-8-stig-baseline-vanilla-rhel-8-4316bb39-df27-4b88-a069-6a6e727c54ee"
    p.customize ["modifyvm", :id, "--cpus", "4"]
    p.customize ["modifyvm", :id, "--memory", "8192"]
    p.customize ["modifyvm", :id, "--accelerate3d", "off"]
    p.customize ["modifyvm", :id, "--accelerate2dvideo", "off"]
    p.customize ["modifyvm", :id, "--audio", "none"]
    p.customize ["modifyvm", :id, "--usbcardreader", "off"]
    p.customize ["modifyvm", :id, "--vrde", "off"]
    p.customize ["modifyvm", :id, "--usb", "off"]
    p.customize ["modifyvm", :id, "--nictype1", "82540EM"]
    p.customize ["modifyvm", :id, "--clipboard", "disabled"]
  end
end
